#!/bin/sh

echo "Running git pre-commit hook"
# Run Detekt before each commit
./gradlew detekt --console=plain
# If Detekt fails, block commit
if [ $? -ne 0 ]; then
  echo "Detekt found issues. Please fix them before committing."
  exit 1
else
  exit 0
fi